### ISSUE TITLE
Kubernetes version 1.11.0 bug

### ISSUE THREAD

**Issue by Bowbee** [spatialos/online-services#153]
Kubernetes version 1.11.0 currently has a bug where line 12 of providers.tf will throw an exception when terraform apply is executed.

This can be avoided currently by pinning the version to 1.10.0 until a fix is found.
This is done by adding version  = "1.10.0" within the provider block.

Reference: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/759
I spotted this while following the guide on Gateway:Deploy.

Thanks :)

**Comment by JoelOtter** [comment]
Hi there, thanks for reporting this. We recommend using Kubernetes version 1.12 or above if you're deploying these services.
